
ci:
  java-version: "21"
  distribution: corretto

files:
  version: release.version

bump:
  enabled: true
  base-branch: main
  label: autobump

release:
  full-release: true
  publish: true

deploy:
  auto-dev: false

docker:
  enabled: true
  image-name: fsamp-gateway
  registry: ghcr.io
  platforms: linux/amd64

sonar:
  enabled: true
  organization: pauszek
  project-key: pauszek_fsamp-gateway
